services:
  database:
    container_name: sqlServer
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Contraseña12345678"
    ports:
      - 1433:1433
  
  backend:
    image: api
    ports: 
      - "80:80"