services:
  database:
    container_name: sqlServer
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Contraseña12345678"
    ports:
      - 1433:1433
    networks:
      - backend
  
  backend:
    image: api
    ports: 
      - 5000:5000
    networks:
      - backend

networks:
  backend: