services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - backend
  
  backend:
    container_name: api
    image: api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports: 
      - 5000:5000
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge