FROM node

RUN npm install -g npm

WORKDIR /Frontend

COPY . .

RUN npm ci

RUN npm run build

# RUN rm -rf src/ static/ emailTemplates/ docker-compose.yml

# COPY . .

# RUN pnpm build

# EXPOSE 5173
# CMD ["node", "build"]